// src/lib/mockData.ts
import { Imovel } from "@/types";

export const mockImoveis: Imovel[] = [
  {
    id: "1",
    titulo: "Apartamento Moderno na Savassi",
    finalidade: "Comprar",
    tipo: "apartamento",
    descricao:
      "Um apartamento incrível com vista panorâmica e acabamento de primeira linha. Ampla sala para dois ambientes, varanda gourmet e cozinha planejada.",
    preco: 1250000,
    valorCondominio: 850,
    valorIptu: 2500,
    quartos: 3,
    suites: 1,
    banheiros: 3,
    vagas: 2,
    area: 120,
    endereco: {
      rua: "Rua dos Inconfidentes",
      numero: "911",
      complemento: "Apto 301",
      bairro: "Savassi",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "30140-120",
    },
    caracteristicasImovel: {
      aceitaPermuta: false,
      churrasqueira: true,
      closet: true,
      dce: false,
      lavabo: true,
      mobiliado: true,
      naPlanta: false,
      alugado: false,
    },
    caracteristicasEdificio: {
      areaDeLazer: true,
      piscina: true,
      piscinaDeRaia: false,
      mercadinho: false,
      lavanderia: true,
      quadraDeTenis: false,
      quadraDeAreia: false,
      quadraEsportiva: true,
      academia: true,
      playground: true,
      salaoDeJogos: true,
      sauna: true,
      portaoEletronico: true,
      precisaDeAutorizacao: true,
      tipoPortaria: "24h",
    },

    proprietario: {
      nome: "Ana Cliente Silva",
      contato: "5531999991111",
      horarioContato: "Após as 18h",
    },
    emDestaque: true,
    status: "Ativo",
    dataCadastro: "2025-06-18",
    fotos: ["/imoveis/imovel-1.jpg"],
  },
  {
    id: "2",
    titulo: "Casa Espaçosa com Quintal no Buritis",
    finalidade: "Comprar",
    tipo: "casa-residencial",
    descricao:
      "Perfeita para famílias que buscam conforto e espaço verde, com área gourmet completa e piscina aquecida.",
    preco: 2500000,
    valorCondominio: 0,
    valorIptu: 4000,
    quartos: 4,
    suites: 2,
    banheiros: 4,
    vagas: 4,
    area: 350,
    endereco: {
      rua: "Rua das Flores",
      numero: "100",
      bairro: "Buritis",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "30494-170",
    },
    caracteristicasImovel: {
      aceitaPermuta: true,
      churrasqueira: true,
      closet: false,
      dce: true,
      lavabo: true,
      mobiliado: false,
      naPlanta: false,
      alugado: false,
    },
    caracteristicasEdificio: {
      areaDeLazer: true,
      piscina: true,
      piscinaDeRaia: false,
      mercadinho: false,
      lavanderia: false,
      quadraDeTenis: false,
      quadraDeAreia: false,
      quadraEsportiva: false,
      academia: false,
      playground: false,
      salaoDeJogos: false,
      sauna: false,
      portaoEletronico: true,
      precisaDeAutorizacao: false,
      tipoPortaria: "Nenhuma",
    },

    proprietario: {
      nome: "Bruno Rocha",
      contato: "5531999992222",
      horarioContato: "Manhã",
    },
    emDestaque: true,
    status: "Ativo",
    dataCadastro: "2025-06-15",
    fotos: ["/imoveis/imovel-2.jpg"],
  },
  {
    id: "3",
    titulo: "Cobertura Duplex para Alugar no Lourdes",
    finalidade: "Alugar",
    tipo: "cobertura",
    descricao:
      "Vista deslumbrante da cidade, com piscina privativa e área de lazer completa no prédio.",
    preco: 12000,
    valorCondominio: 2500,
    valorIptu: 6000,
    quartos: 4,
    suites: 4,
    banheiros: 5,
    vagas: 4,
    area: 350,
    endereco: {
      rua: "Rua da Bahia",
      numero: "2000",
      complemento: "Cob 01",
      bairro: "Lourdes",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "30160-010",
    },
    caracteristicasImovel: {
      aceitaPermuta: false,
      churrasqueira: true,
      closet: true,
      dce: true,
      lavabo: true,
      mobiliado: true,
      naPlanta: false,
      alugado: false,
    },
    caracteristicasEdificio: {
      areaDeLazer: true,
      piscina: true,
      piscinaDeRaia: true,
      mercadinho: true,
      lavanderia: true,
      quadraDeTenis: true,
      quadraDeAreia: false,
      quadraEsportiva: true,
      academia: true,
      playground: true,
      salaoDeJogos: true,
      sauna: true,
      portaoEletronico: true,
      precisaDeAutorizacao: true,
      tipoPortaria: "24h",
    },

    proprietario: {
      nome: "Carla Matos",
      contato: "5531999993333",
      horarioContato: "Qualquer horário",
    },
    emDestaque: true,
    status: "Ativo",
    dataCadastro: "2025-06-10",
    fotos: ["/imoveis/imovel-3.jpg"],
  },
  {
    id: "49578", // Código que usamos no exemplo de busca
    titulo: "Loja Comercial no Centro",
    finalidade: "Alugar",
    tipo: "loja",
    descricao:
      "Ponto comercial excelente com grande fluxo de pessoas, ideal para seu negócio. Loja de frente para a rua.",
    preco: 4500,
    valorCondominio: 150,
    valorIptu: 1800,
    quartos: 0,
    suites: 0,
    banheiros: 1,
    vagas: 0,
    area: 80,
    endereco: {
      rua: "Av. Afonso Pena",
      numero: "500",
      bairro: "Centro",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "30130-000",
    },
    caracteristicasImovel: {
      aceitaPermuta: false,
      churrasqueira: false,
      closet: false,
      dce: false,
      lavabo: false,
      mobiliado: false,
      naPlanta: false,
      alugado: false,
    },
    caracteristicasEdificio: {
      areaDeLazer: false,
      piscina: false,
      piscinaDeRaia: false,
      mercadinho: false,
      lavanderia: false,
      quadraDeTenis: false,
      quadraDeAreia: false,
      quadraEsportiva: false,
      academia: false,
      playground: false,
      salaoDeJogos: false,
      sauna: false,
      portaoEletronico: false,
      precisaDeAutorizacao: false,
      tipoPortaria: "Nenhuma",
    },

    proprietario: {
      nome: "Daniel Investidor",
      contato: "5531999994444",
      horarioContato: "Comercial",
    },
    emDestaque: false,
    status: "Ativo",
    dataCadastro: "2025-06-09",
    fotos: ["/imoveis/imovel-4.jpg"],
  },
  // Adicione os outros 4 imóveis seguindo esta mesma estrutura completa.
];
